// GENERATED by internal/ops/design-revision/council-oils-2026-08/tools/build-oils-package.mjs
//
// One record per oil plate: the museum's own line, the rights token its own
// record asserts, the focal each tier was composed around, and the R2 object
// key of each tier. No image data, so a credit can render while the painting is
// still loading, and no import, so a build that never paints an oil carries
// none of them.
//
// Unlike the July ink plates these carry colour. An oil is the image, not a
// mask: nothing lives in alpha and nothing is recoloured at render.
//
// The rights token differs per file. Never hardcode one.

export interface OilRecord {
  /** `<theme-id>/<council-id>`, or `<theme-id>/lead` for a theme lead. */
  id: string;
  themeId: string;
  /** null on a theme lead, which belongs to the theme rather than a council. */
  councilId: string | null;
  artist: string;
  title: string;
  year: string;
  /** Holding institution, for the credit line. */
  institution: string;
  /** The full collection line including accession, for the rights trail. */
  collection: string;
  objectUrl: string;
  /** Short display token, derived from this record's own licence assertion. */
  rights: string;
  /** The provider's licence sentence as recorded at download. */
  rightsVerbatim: string;
  /** object-position for the square tier on a council card. */
  focal: string;
  /** object-position for the wide tier on a council card. */
  wideFocal: string;
  /** object-position when the wide tier is covered into the 12/5 band. */
  bandFocal: string;
  /** The wide tier is the whole painting on the night field, shown complete. */
  wideMasked: boolean;
  /**
   * R2 object keys, relative to the media root. The name carries the first 8
   * hex of the file's own sha256, because the edge holds these for a year as
   * immutable: a re-bake mints a new name rather than replacing bytes behind a
   * URL a built bundle already points at.
   *
   * A masked wide names the same object as its full tier. They are the same
   * bytes, so it is one fetch and the lightbox opens from cache.
   */
  files: { sq720: string; wide1024: string; full1440: string };
}

export const OIL_RECORDS: Record<string, OilRecord> = {
  "faith-death-mystery/is-this-all-there-is": {
    id: "faith-death-mystery/is-this-all-there-is",
    themeId: "faith-death-mystery",
    councilId: "is-this-all-there-is",
    artist: "El Greco",
    title: "View of Toledo",
    year: "c. 1599-1600",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York, 29.100.6",
    objectUrl: "https://www.metmuseum.org/art/collection/search/436575",
    rights: "CC0",
    rightsVerbatim: "The Metropolitan Museum of Art provides select datasets of information on more than 470,000 artworks in its Collection for unrestricted commercial and noncommercial use. To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this dataset using Creative Commons Zero.",
    focal: "50% 50%",
    wideFocal: "72% 47%",
    bandFocal: "50% 47%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/is-this-all-there-is.full1440.ea49e8e9.webp",
      wide1024: "images/council-oils/faith-death-mystery/is-this-all-there-is.wide1024.8c2c4ce0.webp",
      sq720: "images/council-oils/faith-death-mystery/is-this-all-there-is.sq720.0d5b3971.webp"
    }
  },
  "faith-death-mystery/lead": {
    id: "faith-death-mystery/lead",
    themeId: "faith-death-mystery",
    councilId: null,
    artist: "Gustave Doré",
    title: "L'Énigme",
    year: "1871",
    institution: "Musée d’Orsay, Paris",
    collection: "Musée d’Orsay, Paris",
    objectUrl: "https://commons.wikimedia.org/wiki/File:L'Enigme_de_Gustave_Dor%C3%A9.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName: Public domain; UsageTerms: Public domain; Copyrighted: False; Restrictions: (none)",
    focal: "50% 50%",
    wideFocal: "56% 54%",
    bandFocal: "50% 54%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/lead.full1440.443d047e.webp",
      wide1024: "images/council-oils/faith-death-mystery/lead.wide1024.2772dac9.webp",
      sq720: "images/council-oils/faith-death-mystery/lead.sq720.b30922f9.webp"
    }
  },
  "faith-death-mystery/right-here-right-now": {
    id: "faith-death-mystery/right-here-right-now",
    themeId: "faith-death-mystery",
    councilId: "right-here-right-now",
    artist: "Georges de La Tour",
    title: "The Penitent Magdalen",
    year: "c. 1640",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, 1978.517, Gift of Mr. and Mrs. Charles Wrightsman, 1978",
    objectUrl: "https://www.metmuseum.org/art/collection/search/436839",
    rights: "CC0",
    rightsVerbatim: "The Metropolitan Museum of Art provides select datasets of information on more than 470,000 artworks in its Collection for unrestricted commercial and noncommercial use. To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this dataset using Creative Commons Zero.",
    focal: "50% 50%",
    wideFocal: "50% 88%",
    bandFocal: "50% 88%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/right-here-right-now.full1440.8170b219.webp",
      wide1024: "images/council-oils/faith-death-mystery/right-here-right-now.wide1024.2c321c15.webp",
      sq720: "images/council-oils/faith-death-mystery/right-here-right-now.sq720.661faa1f.webp"
    }
  },
  "faith-death-mystery/the-cathedral-without-walls": {
    id: "faith-death-mystery/the-cathedral-without-walls",
    themeId: "faith-death-mystery",
    councilId: "the-cathedral-without-walls",
    artist: "Frederic Edwin Church",
    title: "Aurora Borealis",
    year: "1865",
    institution: "Smithsonian American Art Museum",
    collection: "Smithsonian American Art Museum, 1911.4.1",
    objectUrl: "https://americanart.si.edu/artwork/aurora-borealis-4806",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName: Public domain; UsageTerms: Public domain; Copyrighted: False; Restrictions: (none)",
    focal: "50% 50%",
    wideFocal: "37% 53%",
    bandFocal: "50% 53%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/the-cathedral-without-walls.full1440.48a2898b.webp",
      wide1024: "images/council-oils/faith-death-mystery/the-cathedral-without-walls.wide1024.4ba43e38.webp",
      sq720: "images/council-oils/faith-death-mystery/the-cathedral-without-walls.sq720.17d6bd38.webp"
    }
  },
  "faith-death-mystery/the-god-after-god": {
    id: "faith-death-mystery/the-god-after-god",
    themeId: "faith-death-mystery",
    councilId: "the-god-after-god",
    artist: "Caspar David Friedrich",
    title: "The Sea of Ice",
    year: "1823-24",
    institution: "Hamburger Kunsthalle",
    collection: "Hamburger Kunsthalle",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Das_Eismeer_-_Hamburger_Kunsthalle_-_02.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName: Public domain; UsageTerms: Public domain; Copyrighted: False; Restrictions: (none)",
    focal: "50% 50%",
    wideFocal: "56% 66%",
    bandFocal: "50% 66%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/the-god-after-god.full1440.29136780.webp",
      wide1024: "images/council-oils/faith-death-mystery/the-god-after-god.wide1024.791c14fd.webp",
      sq720: "images/council-oils/faith-death-mystery/the-god-after-god.sq720.3fae57ac.webp"
    }
  },
  "faith-death-mystery/the-problem-of-evil": {
    id: "faith-death-mystery/the-problem-of-evil",
    themeId: "faith-death-mystery",
    councilId: "the-problem-of-evil",
    artist: "John Martin",
    title: "Pandemonium",
    year: "1841",
    institution: "Musée du Louvre, Paris",
    collection: "Musée du Louvre, Paris",
    objectUrl: "https://commons.wikimedia.org/wiki/File:John_Martin_Le_Pandemonium_Louvre.JPG",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "63% 57%",
    bandFocal: "50% 57%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/the-problem-of-evil.full1440.e5dd907e.webp",
      wide1024: "images/council-oils/faith-death-mystery/the-problem-of-evil.wide1024.32de22d4.webp",
      sq720: "images/council-oils/faith-death-mystery/the-problem-of-evil.sq720.adc6d37e.webp"
    }
  },
  "faith-death-mystery/the-silent-altar": {
    id: "faith-death-mystery/the-silent-altar",
    themeId: "faith-death-mystery",
    councilId: "the-silent-altar",
    artist: "Caspar David Friedrich",
    title: "The Abbey in the Oakwood",
    year: "1809-10",
    institution: "Alte Nationalgalerie, Staatliche Museen zu Berlin",
    collection: "Alte Nationalgalerie, Staatliche Museen zu Berlin",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Abtei_im_Eichwald_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName: Public domain; UsageTerms: Public domain; Copyrighted: False; Restrictions: (none)",
    focal: "50% 50%",
    wideFocal: "50% 60%",
    bandFocal: "50% 60%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/the-silent-altar.full1440.659eb290.webp",
      wide1024: "images/council-oils/faith-death-mystery/the-silent-altar.wide1024.e2c6a8b2.webp",
      sq720: "images/council-oils/faith-death-mystery/the-silent-altar.sq720.c5f0c6a4.webp"
    }
  },
  "faith-death-mystery/the-unfinished-life": {
    id: "faith-death-mystery/the-unfinished-life",
    themeId: "faith-death-mystery",
    councilId: "the-unfinished-life",
    artist: "Arnold Böcklin",
    title: "Self-Portrait with Death Playing the Fiddle",
    year: "1872",
    institution: "Alte Nationalgalerie, Staatliche Museen zu Berlin",
    collection: "Alte Nationalgalerie, Staatliche Museen zu Berlin, A I 633",
    objectUrl: "https://recherche.smb.museum/detail/962057",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName: Public domain; UsageTerms: Public domain; Copyrighted: False; Restrictions: (none)",
    focal: "50% 50%",
    wideFocal: "50% 84%",
    bandFocal: "50% 84%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/faith-death-mystery/the-unfinished-life.full1440.fe52678c.webp",
      wide1024: "images/council-oils/faith-death-mystery/the-unfinished-life.wide1024.6340bf52.webp",
      sq720: "images/council-oils/faith-death-mystery/the-unfinished-life.sq720.b1e2494f.webp"
    }
  },
  "freedom-justice/four-freedoms": {
    id: "freedom-justice/four-freedoms",
    themeId: "freedom-justice",
    councilId: "four-freedoms",
    artist: "Vincent van Gogh",
    title: "Prisoners Exercising (after Gustave Doré)",
    year: "February 1890",
    institution: "Pushkin Museum of Fine Arts, Moscow",
    collection: "Pushkin Museum of Fine Arts, Moscow, acc. Ж-3373",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Vincent_van_Gogh_-_The_Prison_Courtyard_(1890).jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "The author died in 1890, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. This work is in the public domain in the United States because it was published (or registered with the U.S. Copyright Office) before January 1, 1931.",
    focal: "53% 49%",
    wideFocal: "50% 50%",
    bandFocal: "50% 50%",
    wideMasked: true,
    files: {
      full1440: "images/council-oils/freedom-justice/four-freedoms.full1440.d644285d.webp",
      wide1024: "images/council-oils/freedom-justice/four-freedoms.full1440.d644285d.webp",
      sq720: "images/council-oils/freedom-justice/four-freedoms.sq720.c054c40e.webp"
    }
  },
  "freedom-justice/lead": {
    id: "freedom-justice/lead",
    themeId: "freedom-justice",
    councilId: null,
    artist: "Thomas Cole",
    title: "Prometheus Bound",
    year: "1847",
    institution: "Fine Arts Museums of San Francisco",
    collection: "Fine Arts Museums of San Francisco, acc. 1997.28",
    objectUrl: "https://www.famsf.org/artworks/prometheus-bound",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "This is a faithful photographic reproduction of a two-dimensional, public domain work of art. The work of art itself is in the public domain for the following reason: The author died in 1848, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. This work is in the public domain in the United States because it was published (or registered with the U.S. Copyright Office) before January 1, 1931.",
    focal: "46% 26%",
    wideFocal: "75% 33%",
    bandFocal: "50% 0%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/freedom-justice/lead.full1440.ecc5c878.webp",
      wide1024: "images/council-oils/freedom-justice/lead.wide1024.859db029.webp",
      sq720: "images/council-oils/freedom-justice/lead.sq720.537886f5.webp"
    }
  },
  "freedom-justice/the-debt-you-didnt-sign": {
    id: "freedom-justice/the-debt-you-didnt-sign",
    themeId: "freedom-justice",
    councilId: "the-debt-you-didnt-sign",
    artist: "J. M. W. Turner",
    title: "Slave Ship (Slavers Throwing Overboard the Dead and Dying, Typhoon Coming On)",
    year: "1840",
    institution: "Museum of Fine Arts, Boston",
    collection: "Museum of Fine Arts, Boston, acc. 99.22",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Slave-ship.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "This work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. This work is in the public domain in the United States because it was published (or registered with the U.S. Copyright Office) before January 1, 1931. This file has been identified as being free of known restrictions under copyright law, including all related and neighboring rights.",
    focal: "45% 81%",
    wideFocal: "34% 85%",
    bandFocal: "50% 100%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/freedom-justice/the-debt-you-didnt-sign.full1440.dc249fb1.webp",
      wide1024: "images/council-oils/freedom-justice/the-debt-you-didnt-sign.wide1024.4c335f9a.webp",
      sq720: "images/council-oils/freedom-justice/the-debt-you-didnt-sign.sq720.3badc26c.webp"
    }
  },
  "freedom-justice/the-emperor-and-the-fugitive": {
    id: "freedom-justice/the-emperor-and-the-fugitive",
    themeId: "freedom-justice",
    councilId: "the-emperor-and-the-fugitive",
    artist: "Jacques Louis David",
    title: "The Death of Socrates",
    year: "1787",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, acc. 31.45, Catharine Lorillard Wolfe Collection, Wolfe Fund, 1931",
    objectUrl: "https://www.metmuseum.org/art/collection/search/436105",
    rights: "CC0",
    rightsVerbatim: "Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "47% 39%",
    wideFocal: "51% 42%",
    bandFocal: "50% 21%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/freedom-justice/the-emperor-and-the-fugitive.full1440.f46e0646.webp",
      wide1024: "images/council-oils/freedom-justice/the-emperor-and-the-fugitive.wide1024.8f46eb62.webp",
      sq720: "images/council-oils/freedom-justice/the-emperor-and-the-fugitive.sq720.aa2fbea0.webp"
    }
  },
  "freedom-justice/the-inner-citadel": {
    id: "freedom-justice/the-inner-citadel",
    themeId: "freedom-justice",
    councilId: "the-inner-citadel",
    artist: "Rembrandt",
    title: "The Apostle Paul in Prison",
    year: "1627",
    institution: "Staatsgalerie Stuttgart",
    collection: "Staatsgalerie Stuttgart, acc. 746",
    objectUrl: "https://commons.wikimedia.org/wiki/File:1627_Rembrandt_Paulus_im_Gef%C3%A4ngnis_Staatsgalerie_Stuttgart_anagoria.JPG",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "The author died in 1669, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. This work is in the public domain in the United States because it was published (or registered with the U.S. Copyright Office) before January 1, 1931.",
    focal: "58% 19%",
    wideFocal: "60% 32%",
    bandFocal: "50% 0%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/freedom-justice/the-inner-citadel.full1440.a8294a14.webp",
      wide1024: "images/council-oils/freedom-justice/the-inner-citadel.wide1024.c3bb3803.webp",
      sq720: "images/council-oils/freedom-justice/the-inner-citadel.sq720.30aa0ca2.webp"
    }
  },
  "freedom-justice/the-virtue-of-surrender": {
    id: "freedom-justice/the-virtue-of-surrender",
    themeId: "freedom-justice",
    councilId: "the-virtue-of-surrender",
    artist: "Eugène Delacroix",
    title: "Christ Asleep during the Tempest",
    year: "c. 1853",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, acc. 29.100.131, H. O. Havemeyer Collection",
    objectUrl: "https://www.metmuseum.org/art/collection/search/436176",
    rights: "CC0",
    rightsVerbatim: "Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "28% 26%",
    wideFocal: "22% 32%",
    bandFocal: "50% 0%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/freedom-justice/the-virtue-of-surrender.full1440.bb51bc3d.webp",
      wide1024: "images/council-oils/freedom-justice/the-virtue-of-surrender.wide1024.090d5d6b.webp",
      sq720: "images/council-oils/freedom-justice/the-virtue-of-surrender.sq720.784b89b3.webp"
    }
  },
  "freedom-justice/when-silence-becomes-complicity": {
    id: "freedom-justice/when-silence-becomes-complicity",
    themeId: "freedom-justice",
    councilId: "when-silence-becomes-complicity",
    artist: "John Martin",
    title: "Belshazzar's Feast",
    year: "1820",
    institution: "Yale Center for British Art, New Haven",
    collection: "Yale Center for British Art, New Haven, acc. B1981.25.440",
    objectUrl: "https://commons.wikimedia.org/wiki/File:John_Martin_-_Belshazzar%27s_Feast_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "This is a faithful photographic reproduction of a two-dimensional, public domain work of art. The work of art itself is in the public domain for the following reason: The author died in 1854, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. This work is in the public domain in the United States because it was published (or registered with the U.S. Copyright Office) before January 1, 1931.",
    focal: "52% 45%",
    wideFocal: "27% 49%",
    bandFocal: "50% 45%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/freedom-justice/when-silence-becomes-complicity.full1440.667fd40d.webp",
      wide1024: "images/council-oils/freedom-justice/when-silence-becomes-complicity.wide1024.ac7f2da2.webp",
      sq720: "images/council-oils/freedom-justice/when-silence-becomes-complicity.sq720.7667f652.webp"
    }
  },
  "loss-grief/becoming-the-parent": {
    id: "loss-grief/becoming-the-parent",
    themeId: "loss-grief",
    councilId: "becoming-the-parent",
    artist: "Simon Vouet",
    title: "Aeneas and his Father Fleeing Troy",
    year: "c. 1635",
    institution: "The San Diego Museum of Art",
    collection: "The San Diego Museum of Art",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Aeneas_and_his_Father_Fleeing_Troy_by_Simon_Vouet,_San_Diego_Museum_of_Art.JPG",
    rights: "CC0",
    rightsVerbatim: "CC0 — Creative Commons Zero, Public Domain Dedication (photographer's release; the painting is public domain, Vouet died 1649)",
    focal: "43% 40%",
    wideFocal: "51% 44%",
    bandFocal: "50% 44%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/becoming-the-parent.full1440.9a612c50.webp",
      wide1024: "images/council-oils/loss-grief/becoming-the-parent.wide1024.a4e8b02c.webp",
      sq720: "images/council-oils/loss-grief/becoming-the-parent.sq720.8e9095a4.webp"
    }
  },
  "loss-grief/laughing-at-the-abyss": {
    id: "loss-grief/laughing-at-the-abyss",
    themeId: "loss-grief",
    councilId: "laughing-at-the-abyss",
    artist: "Frans Hals",
    title: "Malle Babbe",
    year: "c. 1633-35",
    institution: "Gemäldegalerie, Staatliche Museen zu Berlin",
    collection: "Gemäldegalerie, Staatliche Museen zu Berlin",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Frans_Hals_-_Malle_Babbe_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art; credit: Google Arts & Culture — 8gGg1YQu0B5evw). Artist died 1666.",
    focal: "42% 61%",
    wideFocal: "50% 74%",
    bandFocal: "50% 74%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/laughing-at-the-abyss.full1440.9ae38886.webp",
      wide1024: "images/council-oils/loss-grief/laughing-at-the-abyss.wide1024.32d55346.webp",
      sq720: "images/council-oils/loss-grief/laughing-at-the-abyss.sq720.1f3840e4.webp"
    }
  },
  "loss-grief/lead": {
    id: "loss-grief/lead",
    themeId: "loss-grief",
    councilId: null,
    artist: "Arnold Böcklin",
    title: "Island of the Dead (second version)",
    year: "1880",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York, acc. 26.90, Reisinger Fund, 1926",
    objectUrl: "https://www.metmuseum.org/art/collection/search/435683",
    rights: "CC0",
    rightsVerbatim: "Public Domain (Met Open Access, CC0 1.0 Universal) — API field isPublicDomain: true, rightsAndReproduction empty",
    focal: "52% 87%",
    wideFocal: "45% 92%",
    bandFocal: "50% 92%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/lead.full1440.8d718f05.webp",
      wide1024: "images/council-oils/loss-grief/lead.wide1024.e2c5dafa.webp",
      sq720: "images/council-oils/loss-grief/lead.sq720.2f3ea0ca.webp"
    }
  },
  "loss-grief/the-empty-room": {
    id: "loss-grief/the-empty-room",
    themeId: "loss-grief",
    councilId: "the-empty-room",
    artist: "Vilhelm Hammershøi",
    title: "Moonlight, Strandgade 30",
    year: "1900-1906",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York, acc. 2012.203",
    objectUrl: "https://www.metmuseum.org/art/collection/search/441933",
    rights: "CC0",
    rightsVerbatim: "Public Domain (Met Open Access, CC0 1.0 Universal) — API field isPublicDomain: true, rightsAndReproduction empty",
    focal: "50% 90%",
    wideFocal: "47% 91%",
    bandFocal: "50% 91%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/the-empty-room.full1440.68827c4f.webp",
      wide1024: "images/council-oils/loss-grief/the-empty-room.wide1024.2a43e6ce.webp",
      sq720: "images/council-oils/loss-grief/the-empty-room.sq720.b0b0e8a1.webp"
    }
  },
  "loss-grief/the-meaning-of-pain": {
    id: "loss-grief/the-meaning-of-pain",
    themeId: "loss-grief",
    councilId: "the-meaning-of-pain",
    artist: "Gustave Moreau",
    title: "Prométhée (Cat. 196)",
    year: "1868",
    institution: "Musée national Gustave Moreau, Paris",
    collection: "Musée national Gustave Moreau, Paris",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Gustave_Moreau_006.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art; credit: The Yorck Project (2002) 10.000 Meisterwerke der Malerei (DVD-ROM), distributed by DIRECTMEDIA Publishing GmbH). Artist died 1898.",
    focal: "50% 41%",
    wideFocal: "50% 48%",
    bandFocal: "50% 48%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/the-meaning-of-pain.full1440.7a3309d3.webp",
      wide1024: "images/council-oils/loss-grief/the-meaning-of-pain.wide1024.f9aa0a3d.webp",
      sq720: "images/council-oils/loss-grief/the-meaning-of-pain.sq720.7895733b.webp"
    }
  },
  "loss-grief/the-public-wreckage": {
    id: "loss-grief/the-public-wreckage",
    themeId: "loss-grief",
    councilId: "the-public-wreckage",
    artist: "John Vanderlyn",
    title: "Caius Marius amid the Ruins of Carthage",
    year: "1807",
    institution: "Fine Arts Museums of San Francisco, de Young",
    collection: "Fine Arts Museums of San Francisco, de Young",
    objectUrl: "https://commons.wikimedia.org/wiki/File:John_Vanderlyn_-_Caius_Marius_Amid_the_Ruins_of_Carthage_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art; credit: ogE6KiwPbUy4qw at Google Cultural Institute maximum zoom level). Artist died 1852.",
    focal: "52% 40%",
    wideFocal: "39% 55%",
    bandFocal: "50% 55%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/the-public-wreckage.full1440.44cfae5b.webp",
      wide1024: "images/council-oils/loss-grief/the-public-wreckage.wide1024.9eefbc70.webp",
      sq720: "images/council-oils/loss-grief/the-public-wreckage.sq720.5d662763.webp"
    }
  },
  "loss-grief/the-uninvited-guest": {
    id: "loss-grief/the-uninvited-guest",
    themeId: "loss-grief",
    councilId: "the-uninvited-guest",
    artist: "Francisco de Goya",
    title: "Self-Portrait with Dr. Arrieta",
    year: "1820",
    institution: "Minneapolis Institute of Art",
    collection: "Minneapolis Institute of Art, acc. 52.14, The Ethel Morrison Van Derlip Fund",
    objectUrl: "https://collections.artsmia.org/art/1226/self-portrait-with-dr-arrieta-francisco-jose-de-goya-y-lucientes",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. MIA object record 1226: rights_type \"Public Domain\", public_access 1, Rights_Image_Display \"Full\". File pulled from the museum's own image on Wikimedia Commons (credit: artsmia.org), licence line: Public domain / Public domain.",
    focal: "34% 33%",
    wideFocal: "58% 37%",
    bandFocal: "50% 37%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/the-uninvited-guest.full1440.c47ed9a9.webp",
      wide1024: "images/council-oils/loss-grief/the-uninvited-guest.wide1024.94fd13c6.webp",
      sq720: "images/council-oils/loss-grief/the-uninvited-guest.sq720.f6f1477f.webp"
    }
  },
  "loss-grief/what-carried-you-through": {
    id: "loss-grief/what-carried-you-through",
    themeId: "loss-grief",
    councilId: "what-carried-you-through",
    artist: "Ivan (Hovhannes) Aivazovsky",
    title: "The Ninth Wave",
    year: "1850",
    institution: "State Russian Museum, St Petersburg",
    collection: "State Russian Museum, St Petersburg",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Hovhannes_Aivazovsky_-_The_Ninth_Wave_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art; credit: jgHuL-7yxgrOSw at Google Cultural Institute maximum zoom level). Artist died 1900.",
    focal: "34% 81%",
    wideFocal: "41% 83%",
    bandFocal: "50% 83%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/loss-grief/what-carried-you-through.full1440.3b013cbf.webp",
      wide1024: "images/council-oils/loss-grief/what-carried-you-through.wide1024.069b5e88.webp",
      sq720: "images/council-oils/loss-grief/what-carried-you-through.sq720.3d179ce0.webp"
    }
  },
  "love-connection/alone-in-the-room-full-of-people": {
    id: "love-connection/alone-in-the-room-full-of-people",
    themeId: "love-connection",
    councilId: "alone-in-the-room-full-of-people",
    artist: "Edvard Munch",
    title: "Evening on Karl Johan Street",
    year: "1892",
    institution: "KODE Art Museums, Bergen (Rasmus Meyer Collection)",
    collection: "KODE Art Museums, Bergen (Rasmus Meyer Collection), RMS.M.00245",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Edvard_Munch_-_Evening_on_Karl_Johan_Street_(1892).jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1944; published before 1 January 1931 in the United States.",
    focal: "50% 48%",
    wideFocal: "41% 45%",
    bandFocal: "50% 45%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/alone-in-the-room-full-of-people.full1440.a61d50ec.webp",
      wide1024: "images/council-oils/love-connection/alone-in-the-room-full-of-people.wide1024.3a9640ab.webp",
      sq720: "images/council-oils/love-connection/alone-in-the-room-full-of-people.sq720.a25d46dd.webp"
    }
  },
  "love-connection/choosing-to-be-alone": {
    id: "love-connection/choosing-to-be-alone",
    themeId: "love-connection",
    councilId: "choosing-to-be-alone",
    artist: "Pieter Bruegel the Elder",
    title: "The Misanthrope",
    year: "1568",
    institution: "Museo di Capodimonte, Naples",
    collection: "Museo di Capodimonte, Naples, Q16",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Pieter_Bruegel_d._%C3%84._035-2.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art, Yorck Project). Artist died 1569.",
    focal: "50% 50%",
    wideFocal: "50% 50%",
    bandFocal: "50% 50%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/choosing-to-be-alone.full1440.057066c6.webp",
      wide1024: "images/council-oils/love-connection/choosing-to-be-alone.wide1024.31a2e680.webp",
      sq720: "images/council-oils/love-connection/choosing-to-be-alone.sq720.cf5f4661.webp"
    }
  },
  "love-connection/lead": {
    id: "love-connection/lead",
    themeId: "love-connection",
    councilId: null,
    artist: "Arnold Böcklin",
    title: "Odysseus and Calypso",
    year: "1882",
    institution: "Kunstmuseum Basel",
    collection: "Kunstmuseum Basel, acc. 108",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Arnold_B%C3%B6cklin_008.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1901; published before 1 January 1931 in the United States.",
    focal: "45% 42%",
    wideFocal: "44% 50%",
    bandFocal: "50% 50%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/lead.full1440.5b0d474a.webp",
      wide1024: "images/council-oils/love-connection/lead.wide1024.331da271.webp",
      sq720: "images/council-oils/love-connection/lead.sq720.f670f604.webp"
    }
  },
  "love-connection/the-green-eyed-god": {
    id: "love-connection/the-green-eyed-god",
    themeId: "love-connection",
    councilId: "the-green-eyed-god",
    artist: "Edvard Munch",
    title: "Jealousy",
    year: "1907",
    institution: "Munchmuseet, Oslo",
    collection: "Munchmuseet, Oslo, MM.M.00447",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Edvard_Munch_-_Jealousy_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1944; published before 1 January 1931 in the United States.",
    focal: "51% 32%",
    wideFocal: "34% 43%",
    bandFocal: "50% 43%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/the-green-eyed-god.full1440.d8ff74af.webp",
      wide1024: "images/council-oils/love-connection/the-green-eyed-god.wide1024.53e1d71b.webp",
      sq720: "images/council-oils/love-connection/the-green-eyed-god.sq720.44777058.webp"
    }
  },
  "love-connection/the-mask-behind-the-face": {
    id: "love-connection/the-mask-behind-the-face",
    themeId: "love-connection",
    councilId: "the-mask-behind-the-face",
    artist: "Georges de La Tour",
    title: "The Cheat with the Ace of Clubs",
    year: "c. 1630-34",
    institution: "Kimbell Art Museum, Fort Worth",
    collection: "Kimbell Art Museum, Fort Worth, acc. AP 1981.06",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Georges_de_La_Tour_-_The_Cheat_with_the_Ace_of_Clubs_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1652; published before 1 January 1931 in the United States.",
    focal: "34% 31%",
    wideFocal: "21% 34%",
    bandFocal: "50% 34%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/the-mask-behind-the-face.full1440.8d0644d0.webp",
      wide1024: "images/council-oils/love-connection/the-mask-behind-the-face.wide1024.b36f7692.webp",
      sq720: "images/council-oils/love-connection/the-mask-behind-the-face.sq720.093610ce.webp"
    }
  },
  "love-connection/the-trouble-with-desire": {
    id: "love-connection/the-trouble-with-desire",
    themeId: "love-connection",
    councilId: "the-trouble-with-desire",
    artist: "Franz von Stuck",
    title: "The Kiss of the Sphinx",
    year: "1895",
    institution: "Szépművészeti Múzeum / Museum of Fine Arts, Budapest",
    collection: "Szépművészeti Múzeum / Museum of Fine Arts, Budapest, acc. 124.B",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Franz_von_Stuck_-_The_Kiss_of_the_Sphinx_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1928; published before 1 January 1931 in the United States.",
    focal: "44% 63%",
    wideFocal: "22% 64%",
    bandFocal: "50% 64%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/the-trouble-with-desire.full1440.7b8b9489.webp",
      wide1024: "images/council-oils/love-connection/the-trouble-with-desire.wide1024.04811fc2.webp",
      sq720: "images/council-oils/love-connection/the-trouble-with-desire.sq720.93f3e981.webp"
    }
  },
  "love-connection/the-undoing-of-two": {
    id: "love-connection/the-undoing-of-two",
    themeId: "love-connection",
    councilId: "the-undoing-of-two",
    artist: "Edvard Munch",
    title: "Separation",
    year: "1896",
    institution: "Munchmuseet, Oslo",
    collection: "Munchmuseet, Oslo, MM.M.00024",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Edvard_Munch_-_Separation_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1944; published before 1 January 1931 in the United States.",
    focal: "35% 27%",
    wideFocal: "24% 29%",
    bandFocal: "50% 29%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/the-undoing-of-two.full1440.3571992a.webp",
      wide1024: "images/council-oils/love-connection/the-undoing-of-two.wide1024.da1639d9.webp",
      sq720: "images/council-oils/love-connection/the-undoing-of-two.sq720.879103e5.webp"
    }
  },
  "love-connection/where-do-you-belong": {
    id: "love-connection/where-do-you-belong",
    themeId: "love-connection",
    councilId: "where-do-you-belong",
    artist: "Ilya Repin",
    title: "They Did Not Expect Him",
    year: "1884-88",
    institution: "State Tretyakov Gallery, Moscow",
    collection: "State Tretyakov Gallery, Moscow",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Ilya_Repin_Unexpected_visitors.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain (Wikimedia Commons PD-Art). Artist died 1930.",
    focal: "50% 50%",
    wideFocal: "50% 50%",
    bandFocal: "50% 50%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/love-connection/where-do-you-belong.full1440.7a16d0e2.webp",
      wide1024: "images/council-oils/love-connection/where-do-you-belong.wide1024.d99b7b11.webp",
      sq720: "images/council-oils/love-connection/where-do-you-belong.sq720.41146808.webp"
    }
  },
  "meaning-purpose/lead": {
    id: "meaning-purpose/lead",
    themeId: "meaning-purpose",
    councilId: null,
    artist: "Tiziano Vecellio (Titian)",
    title: "Sisyphus",
    year: "c. 1548-49",
    institution: "Museo del Prado, Madrid",
    collection: "Museo del Prado, Madrid",
    objectUrl: "https://www.museodelprado.es/coleccion/obra-de-arte/sisifo/e7a0e0fa-e0b8-4bdd-bc1d-2f4c00b1a41b",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "63% 58%",
    bandFocal: "50% 58%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/lead.full1440.0576b3c8.webp",
      wide1024: "images/council-oils/meaning-purpose/lead.wide1024.0c86fa36.webp",
      sq720: "images/council-oils/meaning-purpose/lead.sq720.07c00fea.webp"
    }
  },
  "meaning-purpose/the-blank-page": {
    id: "meaning-purpose/the-blank-page",
    themeId: "meaning-purpose",
    councilId: "the-blank-page",
    artist: "Caspar David Friedrich",
    title: "Wanderer above the Sea of Fog (Der Wanderer ueber dem Nebelmeer)",
    year: "c. 1817",
    institution: "Hamburger Kunsthalle",
    collection: "Hamburger Kunsthalle",
    objectUrl: "https://online-sammlung.hamburger-kunsthalle.de/de/objekt/HK-5161",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "50% 50%",
    bandFocal: "50% 50%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/the-blank-page.full1440.99deae6b.webp",
      wide1024: "images/council-oils/meaning-purpose/the-blank-page.wide1024.8f1c9003.webp",
      sq720: "images/council-oils/meaning-purpose/the-blank-page.sq720.c392e24d.webp"
    }
  },
  "meaning-purpose/the-calling-that-wont-shut-up": {
    id: "meaning-purpose/the-calling-that-wont-shut-up",
    themeId: "meaning-purpose",
    councilId: "the-calling-that-wont-shut-up",
    artist: "Jules Bastien-Lepage",
    title: "Joan of Arc",
    year: "1879",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York",
    objectUrl: "https://www.metmuseum.org/art/collection/search/435621",
    rights: "CC0",
    rightsVerbatim: "CC0. usage terms: Creative Commons Zero, Public Domain Dedication. http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    focal: "50% 50%",
    wideFocal: "65% 60%",
    bandFocal: "50% 60%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/the-calling-that-wont-shut-up.full1440.d371de4c.webp",
      wide1024: "images/council-oils/meaning-purpose/the-calling-that-wont-shut-up.wide1024.a2f1da66.webp",
      sq720: "images/council-oils/meaning-purpose/the-calling-that-wont-shut-up.sq720.06e04292.webp"
    }
  },
  "meaning-purpose/the-life-you-think-you-want": {
    id: "meaning-purpose/the-life-you-think-you-want",
    themeId: "meaning-purpose",
    councilId: "the-life-you-think-you-want",
    artist: "Thomas Cole",
    title: "The Voyage of Life: Youth",
    year: "1842",
    institution: "National Gallery of Art, Washington",
    collection: "National Gallery of Art, Washington",
    objectUrl: "https://www.nga.gov/artworks/52451-voyage-life-youth",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "35% 54%",
    bandFocal: "50% 54%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/the-life-you-think-you-want.full1440.eaea26d5.webp",
      wide1024: "images/council-oils/meaning-purpose/the-life-you-think-you-want.wide1024.1a841f40.webp",
      sq720: "images/council-oils/meaning-purpose/the-life-you-think-you-want.sq720.c5ad42c1.webp"
    }
  },
  "meaning-purpose/the-price-of-everything": {
    id: "meaning-purpose/the-price-of-everything",
    themeId: "meaning-purpose",
    councilId: "the-price-of-everything",
    artist: "Rembrandt Harmenszoon van Rijn",
    title: "The Parable of the Rich Fool",
    year: "1627",
    institution: "Gemaeldegalerie, Staatliche Museen zu Berlin",
    collection: "Gemaeldegalerie, Staatliche Museen zu Berlin",
    objectUrl: "https://recherche.smb.museum/detail/865254",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "45% 51%",
    bandFocal: "50% 51%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/the-price-of-everything.full1440.9acfb1c5.webp",
      wide1024: "images/council-oils/meaning-purpose/the-price-of-everything.wide1024.14841810.webp",
      sq720: "images/council-oils/meaning-purpose/the-price-of-everything.sq720.befd8e02.webp"
    }
  },
  "meaning-purpose/the-question-behind-every-question": {
    id: "meaning-purpose/the-question-behind-every-question",
    themeId: "meaning-purpose",
    councilId: "the-question-behind-every-question",
    artist: "Elihu Vedder",
    title: "The Questioner of the Sphinx",
    year: "1863",
    institution: "Museum of Fine Arts, Boston",
    collection: "Museum of Fine Arts, Boston",
    objectUrl: "https://collections.mfa.org/objects/31296",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "60% 50%",
    bandFocal: "50% 50%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/the-question-behind-every-question.full1440.4de47474.webp",
      wide1024: "images/council-oils/meaning-purpose/the-question-behind-every-question.wide1024.541daea3.webp",
      sq720: "images/council-oils/meaning-purpose/the-question-behind-every-question.sq720.b75fda70.webp"
    }
  },
  "meaning-purpose/what-you-leave-behind": {
    id: "meaning-purpose/what-you-leave-behind",
    themeId: "meaning-purpose",
    councilId: "what-you-leave-behind",
    artist: "Thomas Cole",
    title: "The Course of Empire: Desolation",
    year: "1836",
    institution: "New-York Historical Society",
    collection: "New-York Historical Society",
    objectUrl: "https://www.nyhistory.org/exhibit/course-empire-desolation",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "37% 54%",
    bandFocal: "50% 54%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/what-you-leave-behind.full1440.08786f1d.webp",
      wide1024: "images/council-oils/meaning-purpose/what-you-leave-behind.wide1024.a1b7db42.webp",
      sq720: "images/council-oils/meaning-purpose/what-you-leave-behind.sq720.82a8a126.webp"
    }
  },
  "meaning-purpose/why-do-i-keep-going-back": {
    id: "meaning-purpose/why-do-i-keep-going-back",
    themeId: "meaning-purpose",
    councilId: "why-do-i-keep-going-back",
    artist: "John William Waterhouse",
    title: "Circe Offering the Cup to Ulysses",
    year: "1891",
    institution: "Gallery Oldham, Oldham",
    collection: "Gallery Oldham, Oldham",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Circe_Offering_the_Cup_to_Odysseus_(2457_x_4023px_ed.).jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain. usage terms: Public domain",
    focal: "50% 50%",
    wideFocal: "48% 65%",
    bandFocal: "50% 65%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/meaning-purpose/why-do-i-keep-going-back.full1440.badcaebe.webp",
      wide1024: "images/council-oils/meaning-purpose/why-do-i-keep-going-back.wide1024.b8dbf892.webp",
      sq720: "images/council-oils/meaning-purpose/why-do-i-keep-going-back.sq720.c9ad9259.webp"
    }
  },
  "mind-creativity/lead": {
    id: "mind-creativity/lead",
    themeId: "mind-creativity",
    councilId: null,
    artist: "Rembrandt van Rijn",
    title: "Aristotle with a Bust of Homer",
    year: "1653",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York, acc. 61.198",
    objectUrl: "https://www.metmuseum.org/art/collection/search/437394",
    rights: "CC0",
    rightsVerbatim: "isPublicDomain: true; rightsAndReproduction: \"\". Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "50% 50%",
    wideFocal: "40% 63%",
    bandFocal: "50% 63%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/lead.full1440.1fa72ebd.webp",
      wide1024: "images/council-oils/mind-creativity/lead.wide1024.725c9375.webp",
      sq720: "images/council-oils/mind-creativity/lead.sq720.a0fdaa67.webp"
    }
  },
  "mind-creativity/the-discipline-of-seeing": {
    id: "mind-creativity/the-discipline-of-seeing",
    themeId: "mind-creativity",
    councilId: "the-discipline-of-seeing",
    artist: "Adriaen Coorte",
    title: "Still Life with Asparagus",
    year: "1697",
    institution: "Rijksmuseum, Amsterdam",
    collection: "Rijksmuseum, Amsterdam, obj. SK-A-2099",
    objectUrl: "https://www.rijksmuseum.nl/en/collection/SK-A-2099",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName: \"Public domain\"; UsageTerms: \"Public domain\"",
    focal: "50% 50%",
    wideFocal: "50% 76%",
    bandFocal: "50% 76%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/the-discipline-of-seeing.full1440.0245c13f.webp",
      wide1024: "images/council-oils/mind-creativity/the-discipline-of-seeing.wide1024.4f4b1925.webp",
      sq720: "images/council-oils/mind-creativity/the-discipline-of-seeing.sq720.b2f3b22d.webp"
    }
  },
  "mind-creativity/the-freedom-of-less": {
    id: "mind-creativity/the-freedom-of-less",
    themeId: "mind-creativity",
    councilId: "the-freedom-of-less",
    artist: "Vilhelm Hammershøi",
    title: "Interior. The Music Room, Strandgade 30",
    year: "1907",
    institution: "The Art Institute of Chicago",
    collection: "The Art Institute of Chicago, acc. 2023.1322",
    objectUrl: "https://www.artic.edu/artworks/270002",
    rights: "CC0",
    rightsVerbatim: "is_public_domain: true; copyright_notice: null. All other data in this response is licensed under a Creative Commons Zero (CC0) 1.0 designation and the Terms and Conditions of artic.edu.",
    focal: "50% 50%",
    wideFocal: "52% 43%",
    bandFocal: "50% 43%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/the-freedom-of-less.full1440.0a33887c.webp",
      wide1024: "images/council-oils/mind-creativity/the-freedom-of-less.wide1024.7c192243.webp",
      sq720: "images/council-oils/mind-creativity/the-freedom-of-less.sq720.c328976f.webp"
    }
  },
  "mind-creativity/the-ghost-in-the-engine": {
    id: "mind-creativity/the-ghost-in-the-engine",
    themeId: "mind-creativity",
    councilId: "the-ghost-in-the-engine",
    artist: "Jean-Léon Gérôme",
    title: "Pygmalion and Galatea",
    year: "c. 1890",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, acc. 27.200",
    objectUrl: "https://www.metmuseum.org/art/collection/search/436483",
    rights: "CC0",
    rightsVerbatim: "isPublicDomain: true; rightsAndReproduction: \"\". Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "50% 50%",
    wideFocal: "50% 50%",
    bandFocal: "50% 50%",
    wideMasked: true,
    files: {
      full1440: "images/council-oils/mind-creativity/the-ghost-in-the-engine.full1440.d0e29f4a.webp",
      wide1024: "images/council-oils/mind-creativity/the-ghost-in-the-engine.full1440.d0e29f4a.webp",
      sq720: "images/council-oils/mind-creativity/the-ghost-in-the-engine.sq720.0c2dba24.webp"
    }
  },
  "mind-creativity/the-mind-that-wont-be-quiet": {
    id: "mind-creativity/the-mind-that-wont-be-quiet",
    themeId: "mind-creativity",
    councilId: "the-mind-that-wont-be-quiet",
    artist: "Albert Pinkham Ryder",
    title: "The Race Track (Death on a Pale Horse)",
    year: "c. 1896-1908",
    institution: "The Cleveland Museum of Art",
    collection: "The Cleveland Museum of Art, acc. 1928.8",
    objectUrl: "https://www.clevelandart.org/art/1928.8",
    rights: "CC0",
    rightsVerbatim: "share_license_status: \"CC0\"; copyright: null",
    focal: "50% 50%",
    wideFocal: "48% 49%",
    bandFocal: "50% 49%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/the-mind-that-wont-be-quiet.full1440.75939d2c.webp",
      wide1024: "images/council-oils/mind-creativity/the-mind-that-wont-be-quiet.wide1024.5d0fc530.webp",
      sq720: "images/council-oils/mind-creativity/the-mind-that-wont-be-quiet.sq720.0960183a.webp"
    }
  },
  "mind-creativity/the-serious-work-of-play": {
    id: "mind-creativity/the-serious-work-of-play",
    themeId: "mind-creativity",
    councilId: "the-serious-work-of-play",
    artist: "Jean Siméon Chardin",
    title: "Soap Bubbles",
    year: "c. 1733-34",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, acc. 49.24",
    objectUrl: "https://www.metmuseum.org/art/collection/search/435888",
    rights: "CC0",
    rightsVerbatim: "isPublicDomain: true; rightsAndReproduction: \"\". Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "50% 50%",
    wideFocal: "38% 0%",
    bandFocal: "50% 0%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/the-serious-work-of-play.full1440.44dd4f99.webp",
      wide1024: "images/council-oils/mind-creativity/the-serious-work-of-play.wide1024.70701793.webp",
      sq720: "images/council-oils/mind-creativity/the-serious-work-of-play.sq720.d7c22367.webp"
    }
  },
  "mind-creativity/the-vessel-and-the-flame": {
    id: "mind-creativity/the-vessel-and-the-flame",
    themeId: "mind-creativity",
    councilId: "the-vessel-and-the-flame",
    artist: "Vincent van Gogh",
    title: "Cypresses",
    year: "1889",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, acc. 49.30",
    objectUrl: "https://www.metmuseum.org/art/collection/search/437980",
    rights: "CC0",
    rightsVerbatim: "isPublicDomain: true; rightsAndReproduction: \"\". Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "50% 50%",
    wideFocal: "50% 89%",
    bandFocal: "50% 89%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/the-vessel-and-the-flame.full1440.a1fb6084.webp",
      wide1024: "images/council-oils/mind-creativity/the-vessel-and-the-flame.wide1024.5ace56a1.webp",
      sq720: "images/council-oils/mind-creativity/the-vessel-and-the-flame.sq720.7cee3247.webp"
    }
  },
  "mind-creativity/when-words-arent-enough": {
    id: "mind-creativity/when-words-arent-enough",
    themeId: "mind-creativity",
    councilId: "when-words-arent-enough",
    artist: "Caspar David Friedrich",
    title: "Two Men Contemplating the Moon",
    year: "c. 1825-30",
    institution: "The Metropolitan Museum of Art",
    collection: "The Metropolitan Museum of Art, acc. 2000.51",
    objectUrl: "https://www.metmuseum.org/art/collection/search/438417",
    rights: "CC0",
    rightsVerbatim: "isPublicDomain: true; rightsAndReproduction: \"\". Creative Commons Zero (CC0). To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this image.",
    focal: "50% 50%",
    wideFocal: "39% 51%",
    bandFocal: "50% 51%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/mind-creativity/when-words-arent-enough.full1440.e48bab00.webp",
      wide1024: "images/council-oils/mind-creativity/when-words-arent-enough.wide1024.8b93592e.webp",
      sq720: "images/council-oils/mind-creativity/when-words-arent-enough.sq720.418ce7f0.webp"
    }
  },
  "moral-life/how-do-you-forgive": {
    id: "moral-life/how-do-you-forgive",
    themeId: "moral-life",
    councilId: "how-do-you-forgive",
    artist: "Rembrandt",
    title: "The Return of the Prodigal Son",
    year: "c. 1668",
    institution: "State Hermitage Museum, St Petersburg",
    collection: "State Hermitage Museum, St Petersburg, acc. 742",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Rembrandt_Harmensz_van_Rijn_-_Return_of_the_Prodigal_Son_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "This is a faithful photographic reproduction of a two-dimensional, public domain work of art. The author died in 1669, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer.",
    focal: "34% 34%",
    wideFocal: "34% 34%",
    bandFocal: "50% 34%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/how-do-you-forgive.full1440.f8b2dd64.webp",
      wide1024: "images/council-oils/moral-life/how-do-you-forgive.wide1024.83cc8de0.webp",
      sq720: "images/council-oils/moral-life/how-do-you-forgive.sq720.752490ae.webp"
    }
  },
  "moral-life/lead": {
    id: "moral-life/lead",
    themeId: "moral-life",
    councilId: null,
    artist: "Johannes Vermeer",
    title: "Woman Holding a Balance",
    year: "c. 1664",
    institution: "National Gallery of Art, Washington",
    collection: "National Gallery of Art, Washington, acc. 1942.9.97",
    objectUrl: "https://www.nga.gov/artworks/1236-woman-holding-balance",
    rights: "CC0",
    rightsVerbatim: "To the extent permitted by law, the National Gallery of Art waives any copyright or related rights that it might have in this dataset and is releasing this dataset under the Creative Commons Zero designation.",
    focal: "62% 30%",
    wideFocal: "62% 30%",
    bandFocal: "50% 30%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/lead.full1440.04721d71.webp",
      wide1024: "images/council-oils/moral-life/lead.wide1024.a5441938.webp",
      sq720: "images/council-oils/moral-life/lead.sq720.ba2f6565.webp"
    }
  },
  "moral-life/raising-the-next-one": {
    id: "moral-life/raising-the-next-one",
    themeId: "moral-life",
    councilId: "raising-the-next-one",
    artist: "Anthony van Dyck",
    title: "Daedalus and Icarus",
    year: "c. 1615-25",
    institution: "Art Gallery of Ontario, Toronto",
    collection: "Art Gallery of Ontario, Toronto, acc. 2556",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Anthony_van_Dyck_-_Daedalus_and_Icarus_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "The author died in 1641, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. Public domain in the United States because it was published before 1931.",
    focal: "56% 30%",
    wideFocal: "56% 30%",
    bandFocal: "50% 30%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/raising-the-next-one.full1440.dcdef96a.webp",
      wide1024: "images/council-oils/moral-life/raising-the-next-one.wide1024.2935bbe5.webp",
      sq720: "images/council-oils/moral-life/raising-the-next-one.sq720.5d29fd52.webp"
    }
  },
  "moral-life/the-examined-life": {
    id: "moral-life/the-examined-life",
    themeId: "moral-life",
    councilId: "the-examined-life",
    artist: "Salvator Rosa",
    title: "Democritus in Meditation",
    year: "1650",
    institution: "Statens Museum for Kunst, Copenhagen",
    collection: "Statens Museum for Kunst, Copenhagen, KMS4112",
    objectUrl: "https://open.smk.dk/en/artwork/image/KMS4112",
    rights: "Public Domain Mark 1.0",
    rightsVerbatim: "Public domain under Creative Commons Mark 1.0 (https://creativecommons.org/publicdomain/mark/1.0/)",
    focal: "32% 30%",
    wideFocal: "32% 30%",
    bandFocal: "50% 30%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/the-examined-life.full1440.a3c1f15f.webp",
      wide1024: "images/council-oils/moral-life/the-examined-life.wide1024.ba917797.webp",
      sq720: "images/council-oils/moral-life/the-examined-life.sq720.a13770e5.webp"
    }
  },
  "moral-life/the-fear-you-feed": {
    id: "moral-life/the-fear-you-feed",
    themeId: "moral-life",
    councilId: "the-fear-you-feed",
    artist: "Ivan Kramskoi",
    title: "Christ in the Wilderness",
    year: "1872",
    institution: "State Tretyakov Gallery, Moscow",
    collection: "State Tretyakov Gallery, Moscow",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Ivan_Kramskoy_-_%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%BE%D1%81_%D0%B2_%D0%BF%D1%83%D1%81%D1%82%D1%8B%D0%BD%D0%B5_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "LicenseShortName \"Public domain\"; UsageTerms \"Public domain\"; artist \"Ivan Kramskoi (Russian artist, 1837-1887)\"; credit \"Google Arts & Culture — uwEOJTS-uQb5ww\".",
    focal: "52% 26%",
    wideFocal: "52% 26%",
    bandFocal: "50% 26%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/the-fear-you-feed.full1440.5c6811d9.webp",
      wide1024: "images/council-oils/moral-life/the-fear-you-feed.wide1024.d138f511.webp",
      sq720: "images/council-oils/moral-life/the-fear-you-feed.sq720.93fc20c0.webp"
    }
  },
  "moral-life/the-intelligence-of-wounds": {
    id: "moral-life/the-intelligence-of-wounds",
    themeId: "moral-life",
    councilId: "the-intelligence-of-wounds",
    artist: "Caravaggio",
    title: "The Incredulity of Saint Thomas",
    year: "1601-02",
    institution: "Bildergalerie, Sanssouci, Potsdam (SPSG)",
    collection: "Bildergalerie, Sanssouci, Potsdam (SPSG), GK I 5438",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Caravaggio_incredulity.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "The author died in 1610, so this work is in the public domain in its country of origin and other countries and areas where the copyright term is the author’s life plus 100 years or fewer. Also public domain in the United States because it was published before January 1, 1931.",
    focal: "34% 40%",
    wideFocal: "34% 40%",
    bandFocal: "50% 40%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/the-intelligence-of-wounds.full1440.9f24a113.webp",
      wide1024: "images/council-oils/moral-life/the-intelligence-of-wounds.wide1024.52d20db2.webp",
      sq720: "images/council-oils/moral-life/the-intelligence-of-wounds.sq720.f7c4531d.webp"
    }
  },
  "moral-life/the-letting-go": {
    id: "moral-life/the-letting-go",
    themeId: "moral-life",
    councilId: "the-letting-go",
    artist: "Joseph Mallord William Turner",
    title: "The Burning of the Houses of Lords and Commons, 16 October 1834",
    year: "1835",
    institution: "The Cleveland Museum of Art",
    collection: "The Cleveland Museum of Art, 1942.647, Bequest of John L. Severance",
    objectUrl: "https://clevelandart.org/art/1942.647",
    rights: "CC0",
    rightsVerbatim: "CC0",
    focal: "50% 50%",
    wideFocal: "50% 50%",
    bandFocal: "50% 50%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/the-letting-go.full1440.5a08084b.webp",
      wide1024: "images/council-oils/moral-life/the-letting-go.wide1024.1f0dd461.webp",
      sq720: "images/council-oils/moral-life/the-letting-go.sq720.7f29134c.webp"
    }
  },
  "moral-life/what-does-your-anger-want": {
    id: "moral-life/what-does-your-anger-want",
    themeId: "moral-life",
    councilId: "what-does-your-anger-want",
    artist: "Rembrandt",
    title: "Moses Smashing the Tablets of the Law",
    year: "1659",
    institution: "Gemäldegalerie, Staatliche Museen zu Berlin",
    collection: "Gemäldegalerie, Staatliche Museen zu Berlin",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Rembrandt_-_Moses_with_the_Ten_Commandments_-_Google_Art_Project.jpg",
    rights: "Public Domain Mark 1.0",
    rightsVerbatim: "This is a faithful photographic reproduction of a two-dimensional, public domain work of art. The work of art itself is in the public domain. Public domain in the United States because it was published before January 1, 1931. Creative Commons Public Domain Mark 1.0.",
    focal: "50% 28%",
    wideFocal: "50% 28%",
    bandFocal: "50% 28%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/moral-life/what-does-your-anger-want.full1440.cb5d2c90.webp",
      wide1024: "images/council-oils/moral-life/what-does-your-anger-want.wide1024.8429a1be.webp",
      sq720: "images/council-oils/moral-life/what-does-your-anger-want.sq720.25c8346e.webp"
    }
  },
  "who-am-i/lead": {
    id: "who-am-i/lead",
    themeId: "who-am-i",
    councilId: null,
    artist: "Gustave Moreau",
    title: "Oedipus and the Sphinx",
    year: "1864",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York (acc. 21.134.1)",
    objectUrl: "https://www.metmuseum.org/art/collection/search/437153",
    rights: "CC0",
    rightsVerbatim: "Met Collection API: \"isPublicDomain\": true — Met Open Access: \"Creative Commons Zero, Public Domain Dedication\"",
    focal: "50% 50%",
    wideFocal: "52% 57%",
    bandFocal: "50% 57%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/lead.full1440.c0f0d7f0.webp",
      wide1024: "images/council-oils/who-am-i/lead.wide1024.c5150106.webp",
      sq720: "images/council-oils/who-am-i/lead.sq720.23d8e148.webp"
    }
  },
  "who-am-i/the-body-that-carried-you": {
    id: "who-am-i/the-body-that-carried-you",
    themeId: "who-am-i",
    councilId: "the-body-that-carried-you",
    artist: "Rembrandt van Rijn",
    title: "Self-Portrait",
    year: "1660",
    institution: "The Metropolitan Museum of Art, New York",
    collection: "The Metropolitan Museum of Art, New York (acc. 14.40.618)",
    objectUrl: "https://www.metmuseum.org/art/collection/search/437397",
    rights: "CC0",
    rightsVerbatim: "Met Collection API: \"isPublicDomain\": true — Met Open Access: \"Creative Commons Zero, Public Domain Dedication\"",
    focal: "50% 50%",
    wideFocal: "45% 58%",
    bandFocal: "50% 58%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-body-that-carried-you.full1440.a95161ff.webp",
      wide1024: "images/council-oils/who-am-i/the-body-that-carried-you.wide1024.d0c38b79.webp",
      sq720: "images/council-oils/who-am-i/the-body-that-carried-you.sq720.17da03e3.webp"
    }
  },
  "who-am-i/the-gilded-cage-you-built-yourself": {
    id: "who-am-i/the-gilded-cage-you-built-yourself",
    themeId: "who-am-i",
    councilId: "the-gilded-cage-you-built-yourself",
    artist: "Caspar David Friedrich",
    title: "Frau am Fenster (Woman at a Window)",
    year: "1822",
    institution: "Alte Nationalgalerie, Staatliche Museen zu Berlin",
    collection: "Alte Nationalgalerie, Staatliche Museen zu Berlin",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Frau_am_Fenster_(1822).jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "50% 59%",
    bandFocal: "50% 59%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-gilded-cage-you-built-yourself.full1440.9d18b568.webp",
      wide1024: "images/council-oils/who-am-i/the-gilded-cage-you-built-yourself.wide1024.818f2aef.webp",
      sq720: "images/council-oils/who-am-i/the-gilded-cage-you-built-yourself.sq720.1969d147.webp"
    }
  },
  "who-am-i/the-mask-that-speaks": {
    id: "who-am-i/the-mask-that-speaks",
    themeId: "who-am-i",
    councilId: "the-mask-that-speaks",
    artist: "Francisco de Goya",
    title: "The Burial of the Sardine (El entierro de la sardina)",
    year: "1812-14",
    institution: "Real Academia de Bellas Artes de San Fernando, Madrid",
    collection: "Real Academia de Bellas Artes de San Fernando, Madrid",
    objectUrl: "https://commons.wikimedia.org/wiki/File:GOYA_-_Entierro_de_la_Sardina_(Real_Academia_de_Bellas_Artes_de_San_Fernando,_1812-14).jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "50% 58%",
    bandFocal: "50% 58%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-mask-that-speaks.full1440.022516f9.webp",
      wide1024: "images/council-oils/who-am-i/the-mask-that-speaks.wide1024.bcd0ab13.webp",
      sq720: "images/council-oils/who-am-i/the-mask-that-speaks.sq720.1375c90f.webp"
    }
  },
  "who-am-i/the-self-that-isnt-there": {
    id: "who-am-i/the-self-that-isnt-there",
    themeId: "who-am-i",
    councilId: "the-self-that-isnt-there",
    artist: "Caravaggio",
    title: "Narcissus",
    year: "c. 1597-99",
    institution: "Gallerie Nazionali d'Arte Antica, Palazzo Barberini, Rome",
    collection: "Gallerie Nazionali d'Arte Antica, Palazzo Barberini, Rome",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Narcissus-Caravaggio_(1594-96)_edited.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "50% 83%",
    bandFocal: "50% 83%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-self-that-isnt-there.full1440.53a4d907.webp",
      wide1024: "images/council-oils/who-am-i/the-self-that-isnt-there.wide1024.fa47b32f.webp",
      sq720: "images/council-oils/who-am-i/the-self-that-isnt-there.sq720.5d661a96.webp"
    }
  },
  "who-am-i/the-stain-that-stays": {
    id: "who-am-i/the-stain-that-stays",
    themeId: "who-am-i",
    councilId: "the-stain-that-stays",
    artist: "Henry Fuseli (Johann Heinrich Füssli)",
    title: "Lady Macbeth Sleepwalking",
    year: "c. 1784",
    institution: "Musée du Louvre, Paris",
    collection: "Musée du Louvre, Paris (RF 1970 29)",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Lady_Macbeth_somnambule_-_Johann_Heinrich_F%C3%BCssli_-_Mus%C3%A9e_du_Louvre_Peintures_RF_1970_29.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "54% 39%",
    bandFocal: "50% 39%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-stain-that-stays.full1440.c2e8b03c.webp",
      wide1024: "images/council-oils/who-am-i/the-stain-that-stays.wide1024.83a4eeb0.webp",
      sq720: "images/council-oils/who-am-i/the-stain-that-stays.sq720.0730e553.webp"
    }
  },
  "who-am-i/the-story-you-keep-telling": {
    id: "who-am-i/the-story-you-keep-telling",
    themeId: "who-am-i",
    councilId: "the-story-you-keep-telling",
    artist: "William Holman Hunt (with Edward Robert Hughes)",
    title: "The Lady of Shalott",
    year: "c. 1888-1905",
    institution: "Wadsworth Atheneum Museum of Art, Hartford CT",
    collection: "Wadsworth Atheneum Museum of Art, Hartford CT",
    objectUrl: "https://commons.wikimedia.org/wiki/File:The_Lady_of_Shalott_by_William_Holman_Hunt,_c._1890-1905,_oil_on_canvas_-_Wadsworth_Atheneum_-_Hartford,_CT_-_DSC05541.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "34% 44%",
    bandFocal: "50% 44%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-story-you-keep-telling.full1440.a8bc3e18.webp",
      wide1024: "images/council-oils/who-am-i/the-story-you-keep-telling.wide1024.16b32aa4.webp",
      sq720: "images/council-oils/who-am-i/the-story-you-keep-telling.sq720.477d9ce1.webp"
    }
  },
  "who-am-i/the-weight-of-things": {
    id: "who-am-i/the-weight-of-things",
    themeId: "who-am-i",
    councilId: "the-weight-of-things",
    artist: "Antonio de Pereda",
    title: "The Knight's Dream (El sueño del caballero)",
    year: "c. 1650",
    institution: "Real Academia de Bellas Artes de San Fernando, Madrid",
    collection: "Real Academia de Bellas Artes de San Fernando, Madrid",
    objectUrl: "https://commons.wikimedia.org/wiki/File:Antonio_de_Pereda_-_El_sue%C3%B1o_del_caballero_-_Google_Art_Project.jpg",
    rights: "Public domain (PD-Art)",
    rightsVerbatim: "Public domain / Public domain",
    focal: "50% 50%",
    wideFocal: "67% 60%",
    bandFocal: "50% 60%",
    wideMasked: false,
    files: {
      full1440: "images/council-oils/who-am-i/the-weight-of-things.full1440.9dbd6f1f.webp",
      wide1024: "images/council-oils/who-am-i/the-weight-of-things.wide1024.bcddb25b.webp",
      sq720: "images/council-oils/who-am-i/the-weight-of-things.sq720.e872e48c.webp"
    }
  }
};

export default OIL_RECORDS;
