#!/bin/sh
# /docker-entrypoint.d/00-agora-config.sh
#
# Generates /usr/share/nginx/html/config.js from container env vars so one
# published image works for any operator without a rebuild. Runs once per
# container start, before nginx execs (per the nginxinc base image convention
# of executing every *.sh in /docker-entrypoint.d/ first).
#
# Env vars (both optional):
#   AGORA_MEDIA_BASE_URL  public media CDN. Empty = falls back to the
#                         build-time default (https://media.agoracosmica.org).
#   AGORA_AUDIO_API_URL   live audio backend. Empty = live voice disabled,
#                         pre-recorded audio still works.

set -eu

CONFIG_PATH="/usr/share/nginx/html/config.js"

cat > "$CONFIG_PATH" <<EOF
// Generated by docker-entrypoint.sh at container start. Do not edit;
// rebuild and restart the container with new env vars instead.
window.__AGORA_CONFIG__ = {
  mediaBaseUrl: '${AGORA_MEDIA_BASE_URL:-}',
  audioApiUrl: '${AGORA_AUDIO_API_URL:-}'
};
EOF

echo "[agora-config] wrote $CONFIG_PATH (media='${AGORA_MEDIA_BASE_URL:-<empty>}', audio='${AGORA_AUDIO_API_URL:-<empty>}')"
