#!/usr/bin/env tsx
// Build-time script: reads all instruction JSONs → generates prompts/instructions.ts
// Run: npx tsx scripts/bundle-prompts.ts

import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';

const INSTRUCTIONS_DIR = resolve(__dirname, '../../client/src/assets/instructions');
const OUTPUT_FILE = resolve(__dirname, '../src/prompts/instructions.ts');

const MODES = ['free_conversation', 'seed_conversation', 'seed_challenge'];

function main() {
  const figures = readdirSync(INSTRUCTIONS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort();

  console.log(`Bundling instructions for ${figures.length} figures...`);

  const entries: Record<string, string> = {};
  let totalSize = 0;

  for (const figure of figures) {
    for (const mode of MODES) {
      const filePath = join(INSTRUCTIONS_DIR, figure, `${mode}.json`);
      try {
        const raw = readFileSync(filePath, 'utf-8');
        const parsed = JSON.parse(raw);
        const system = parsed.system;
        if (typeof system !== 'string') {
          console.warn(`  SKIP ${figure}/${mode}: no "system" field`);
          continue;
        }
        const key = `${figure}:${mode}`;
        entries[key] = system;
        totalSize += system.length;
        console.log(`  ${key} (${(system.length / 1024).toFixed(1)}KB)`);
      } catch (err) {
        console.warn(`  SKIP ${figure}/${mode}: ${(err as Error).message}`);
      }
    }
  }

  // Generate TypeScript file
  const output = `// AUTO-GENERATED by scripts/bundle-prompts.ts — DO NOT EDIT
// ${Object.keys(entries).length} instruction prompts bundled (${(totalSize / 1024).toFixed(0)}KB total)
// Run: npx tsx scripts/bundle-prompts.ts

export const INSTRUCTIONS: Record<string, string> = ${JSON.stringify(entries, null, 2)};
`;

  writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`\nWrote ${OUTPUT_FILE}`);
  console.log(`  ${Object.keys(entries).length} entries, ${(totalSize / 1024).toFixed(0)}KB`);
}

main();
