// Streaming ZIP writer (STORE method, data descriptors).
//
// Archives are ~400 MB of mp3, so nothing may be buffered: every entry is
// piped straight from R2 while its CRC32 is computed on the fly. That forces
// general purpose bit 3 (sizes and CRC follow the data in a descriptor).
// Total byte count is still known up front because STORE means compressed
// size equals the R2 object size, so the response can carry an exact
// Content-Length.

const SIG_LOCAL = 0x04034b50;
const SIG_DESCRIPTOR = 0x08074b50;
const SIG_CENTRAL = 0x02014b50;
const SIG_END = 0x06054b50;

const LOCAL_HEADER_SIZE = 30;
const DATA_DESCRIPTOR_SIZE = 16;
const CENTRAL_HEADER_SIZE = 46;
const END_RECORD_SIZE = 22;

/** bit 3 = sizes/CRC in data descriptor, bit 11 = UTF-8 file names */
const GP_FLAGS = 0x0008 | 0x0800;
const VERSION_NEEDED = 20; // 2.0 = STORE + directories

/** ZIP32 caps every size field at 4 GB. Archives are ~400 MB, ZIP64 stays out. */
const ZIP32_MAX = 0xffffffff;

export type ZipSource =
  | { kind: 'bytes'; bytes: Uint8Array }
  | { kind: 'r2'; key: string };

export interface ZipEntry {
  /** Path inside the archive. */
  name: string;
  /** Byte length, known before streaming (R2 metadata or generated bytes). */
  size: number;
  /** Modification time, encoded into the DOS fields. */
  modified: Date;
  source: ZipSource;
}

interface PlannedEntry extends ZipEntry {
  nameBytes: Uint8Array;
  dosTime: number;
  dosDate: number;
}

const encoder = new TextEncoder();

function plan(entries: ZipEntry[]): PlannedEntry[] {
  return entries.map((entry) => {
    const { dosTime, dosDate } = toDosDateTime(entry.modified);
    return { ...entry, nameBytes: encoder.encode(entry.name), dosTime, dosDate };
  });
}

/**
 * Exact byte length of the archive these entries produce. Must match what
 * `streamZip` writes, byte for byte.
 */
export function zipByteLength(entries: ZipEntry[]): number {
  let total = END_RECORD_SIZE;
  for (const entry of plan(entries)) {
    if (entry.size > ZIP32_MAX) throw new Error('entry exceeds ZIP32 size limit');
    total += LOCAL_HEADER_SIZE + entry.nameBytes.length + entry.size + DATA_DESCRIPTOR_SIZE;
    total += CENTRAL_HEADER_SIZE + entry.nameBytes.length;
  }
  if (total > ZIP32_MAX) throw new Error('archive exceeds ZIP32 size limit');
  return total;
}

/**
 * Write the archive into `writable`, streaming each R2 object through without
 * buffering. Closes the writer on success, aborts it on any failure so the
 * client sees a truncated download instead of a corrupt archive.
 */
export async function streamZip(
  entries: ZipEntry[],
  bucket: R2Bucket,
  writable: WritableStream<Uint8Array>,
): Promise<void> {
  const planned = plan(entries);
  const writer = writable.getWriter();
  const central: Uint8Array[] = [];
  let offset = 0;

  try {
    for (const entry of planned) {
      const localOffset = offset;
      const header = localHeader(entry);
      await writer.write(header);
      offset += header.length;

      const crc = new Crc32();
      let written = 0;

      if (entry.source.kind === 'bytes') {
        crc.update(entry.source.bytes);
        written = entry.source.bytes.length;
        await writer.write(entry.source.bytes);
      } else {
        const object = await bucket.get(entry.source.key);
        if (!object) throw new Error(`object vanished: ${entry.source.key}`);
        const reader = object.body.getReader();
        for (;;) {
          const { done, value } = await reader.read();
          if (done) break;
          crc.update(value);
          written += value.length;
          await writer.write(value);
        }
      }

      // The plan fixed Content-Length before the first byte moved. A size
      // change under us would desync the response, so fail loudly.
      if (written !== entry.size) throw new Error(`size drift: ${entry.name}`);

      const checksum = crc.value;
      await writer.write(dataDescriptor(checksum, entry.size));
      offset += entry.size + DATA_DESCRIPTOR_SIZE;
      central.push(centralHeader(entry, checksum, localOffset));
    }

    const centralOffset = offset;
    let centralSize = 0;
    for (const record of central) {
      await writer.write(record);
      centralSize += record.length;
    }
    await writer.write(endRecord(central.length, centralSize, centralOffset));
    await writer.close();
  } catch (err) {
    await writer.abort(err).catch(() => { /* client already gone */ });
  }
}

// --- Record builders ---

function localHeader(entry: PlannedEntry): Uint8Array {
  const buf = new Uint8Array(LOCAL_HEADER_SIZE + entry.nameBytes.length);
  const view = new DataView(buf.buffer);
  view.setUint32(0, SIG_LOCAL, true);
  view.setUint16(4, VERSION_NEEDED, true);
  view.setUint16(6, GP_FLAGS, true);
  view.setUint16(8, 0, true); // STORE
  view.setUint16(10, entry.dosTime, true);
  view.setUint16(12, entry.dosDate, true);
  view.setUint32(14, 0, true); // CRC follows in the descriptor
  view.setUint32(18, 0, true); // compressed size, likewise
  view.setUint32(22, 0, true); // uncompressed size, likewise
  view.setUint16(26, entry.nameBytes.length, true);
  view.setUint16(28, 0, true); // no extra field
  buf.set(entry.nameBytes, LOCAL_HEADER_SIZE);
  return buf;
}

function dataDescriptor(crc: number, size: number): Uint8Array {
  const buf = new Uint8Array(DATA_DESCRIPTOR_SIZE);
  const view = new DataView(buf.buffer);
  view.setUint32(0, SIG_DESCRIPTOR, true);
  view.setUint32(4, crc, true);
  view.setUint32(8, size, true);
  view.setUint32(12, size, true);
  return buf;
}

function centralHeader(entry: PlannedEntry, crc: number, localOffset: number): Uint8Array {
  const buf = new Uint8Array(CENTRAL_HEADER_SIZE + entry.nameBytes.length);
  const view = new DataView(buf.buffer);
  view.setUint32(0, SIG_CENTRAL, true);
  view.setUint16(4, VERSION_NEEDED, true); // version made by
  view.setUint16(6, VERSION_NEEDED, true); // version needed
  view.setUint16(8, GP_FLAGS, true);
  view.setUint16(10, 0, true); // STORE
  view.setUint16(12, entry.dosTime, true);
  view.setUint16(14, entry.dosDate, true);
  view.setUint32(16, crc, true);
  view.setUint32(20, entry.size, true); // compressed
  view.setUint32(24, entry.size, true); // uncompressed
  view.setUint16(28, entry.nameBytes.length, true);
  view.setUint16(30, 0, true); // extra field length
  view.setUint16(32, 0, true); // comment length
  view.setUint16(34, 0, true); // disk number
  view.setUint16(36, 0, true); // internal attributes
  view.setUint32(38, 0, true); // external attributes
  view.setUint32(42, localOffset, true);
  buf.set(entry.nameBytes, CENTRAL_HEADER_SIZE);
  return buf;
}

function endRecord(count: number, centralSize: number, centralOffset: number): Uint8Array {
  const buf = new Uint8Array(END_RECORD_SIZE);
  const view = new DataView(buf.buffer);
  view.setUint32(0, SIG_END, true);
  view.setUint16(4, 0, true); // disk number
  view.setUint16(6, 0, true); // disk with central directory
  view.setUint16(8, count, true);
  view.setUint16(10, count, true);
  view.setUint32(12, centralSize, true);
  view.setUint32(16, centralOffset, true);
  view.setUint16(20, 0, true); // no archive comment
  return buf;
}

/** MS-DOS date fields cannot express anything before 1980. */
function toDosDateTime(date: Date): { dosTime: number; dosDate: number } {
  const year = Math.max(date.getUTCFullYear(), 1980);
  const dosTime =
    (date.getUTCHours() << 11) | (date.getUTCMinutes() << 5) | (date.getUTCSeconds() >> 1);
  const dosDate =
    ((year - 1980) << 9) | ((date.getUTCMonth() + 1) << 5) | date.getUTCDate();
  return { dosTime, dosDate };
}

// --- CRC32 ---

// Slice-by-8: eight lookup tables consume 8 bytes per iteration. A byte-wise
// loop is too slow for the ~400 MB an archive pushes through one request.
const CRC_TABLES = buildCrcTables();

function buildCrcTables(): Uint32Array {
  const tables = new Uint32Array(8 * 256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    tables[n] = c >>> 0;
  }
  for (let slice = 1; slice < 8; slice++) {
    for (let n = 0; n < 256; n++) {
      const prev = tables[(slice - 1) * 256 + n];
      tables[slice * 256 + n] = ((prev >>> 8) ^ tables[prev & 0xff]) >>> 0;
    }
  }
  return tables;
}

export class Crc32 {
  private state = 0xffffffff;

  update(chunk: Uint8Array): void {
    const t = CRC_TABLES;
    const len = chunk.length;
    const view = new DataView(chunk.buffer, chunk.byteOffset, chunk.byteLength);
    let c = this.state;
    let i = 0;

    const limit = len - 8;
    while (i <= limit) {
      const lo = view.getUint32(i, true) ^ c;
      const hi = view.getUint32(i + 4, true);
      c =
        t[1792 + (lo & 0xff)] ^
        t[1536 + ((lo >>> 8) & 0xff)] ^
        t[1280 + ((lo >>> 16) & 0xff)] ^
        t[1024 + ((lo >>> 24) & 0xff)] ^
        t[768 + (hi & 0xff)] ^
        t[512 + ((hi >>> 8) & 0xff)] ^
        t[256 + ((hi >>> 16) & 0xff)] ^
        t[hi >>> 24];
      i += 8;
    }
    for (; i < len; i++) {
      c = (c >>> 8) ^ t[(c ^ chunk[i]) & 0xff];
    }

    this.state = c >>> 0;
  }

  get value(): number {
    return (this.state ^ 0xffffffff) >>> 0;
  }
}
