// GENERATED — council art fleet.
// The credit line for every council plate, verbatim from the institution's own
// record. Deliberately free of image data: a detail surface renders the credit
// while the full plate is still loading.
// Provenance: internal/ops/design-revision/council-art-fleet/*.provenance.json

export interface PlateCredit {
  institution: string;
  title: string;
  artist: string;
  date: string;
  objectUrl: string;
  rights: string;
  /** width / height of the full plate */
  aspect: number;
}

export const PLATE_CREDITS: Record<string, PlateCredit> = {
  'alone-in-the-room-full-of-people': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Christ Presented to the People',
    artist: 'Rembrandt (Rembrandt van Rijn)',
    date: '1655',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/356476',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal) — API field isPublicDomain: true',
    aspect: 1.2698,
  },
  'becoming-the-parent': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Aeneas rescuing Anchises, a young boy carrying a lantern at left',
    artist: 'Giovanni Jacopo Caraglio',
    date: 'ca. 1525',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/361942',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.9097,
  },
  'choosing-to-be-alone': {
    institution: 'Rijksmuseum',
    title: 'Heilige Hieronymus in zijn studeervertrek',
    artist: 'anonymous',
    date: '1495 - 1516',
    objectUrl: 'https://www.rijksmuseum.nl/en/collection/RP-P-OB-1856',
    rights: 'Public Domain (Rijksmuseum record asserts https://creativecommons.org/publicdomain/zero/1.0/ on the object and https://creativecommons.org/publicdomain/mark/1.0/ on the image)',
    aspect: 0.6667,
  },
  'four-freedoms': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Prison; a group of men in a dungeon bound in chains and shackles',
    artist: 'Anonymous, after Giorgio Ghisi and Giulio Romano',
    date: 'n.d.',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/367839',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.3967,
  },
  'how-do-you-forgive': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Return of the Prodigal Son, Shown Embracing His Son',
    artist: 'Pietro Testa',
    date: 'ca. 1645',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/399897',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.4314,
  },
  'is-this-all-there-is': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Random Sketches by Hokusai, Volumes 1 to 11',
    artist: 'Katsushika Hokusai 葛飾北斎',
    date: '',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/57804',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.2266,
  },
  'laughing-at-the-abyss': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Razullo - Cucurucu, from "Balli di Sfessania" (Dance of Sfessania)',
    artist: 'Jacques Callot',
    date: 'ca. 1622',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/681433',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.2777,
  },
  'raising-the-next-one': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Madonna on the Crescent, Frontispiece to "The Life of the Virgin"',
    artist: 'Albrecht Dürer',
    date: 'ca. 1511',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/387579',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.8292,
  },
  'right-here-right-now': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Bamboo',
    artist: 'Zheng Xie',
    date: 'Qing dynasty',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/36096',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.3181,
  },
  'the-blank-page': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Erasmus of Rotterdam',
    artist: 'Albrecht Dürer',
    date: '1526',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336231',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7958,
  },
  'the-body-that-carried-you': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Five Legs and Three Feet',
    artist: 'Luca Ciamberlano',
    date: '17th century',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/386108',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7785,
  },
  'the-calling-that-wont-shut-up': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Four Horsemen, from "The Apocalypse"',
    artist: 'Albrecht Dürer',
    date: '1498',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336215',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7361,
  },
  'the-cathedral-without-walls': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Landscape with Four Trees and a Church at Right',
    artist: 'Augustin Hirschvogel',
    date: '1545 (?)',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336260',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.2203,
  },
  'the-debt-you-didnt-sign': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Beggars Receiving Alms at the Door of a House',
    artist: 'Rembrandt (Rembrandt van Rijn)',
    date: '1648',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/391887',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.6896,
  },
  'the-discipline-of-seeing': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Two eyes and two heads',
    artist: 'Wenceslaus Hollar',
    date: '1644–52',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/360713',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 2.3003,
  },
  'the-emperor-and-the-fugitive': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Various figures in procession, from "The Triumph of Caesar"',
    artist: 'Jacob of Strasbourg, after Andrea Mantegna',
    date: '1504',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/348326',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.2609,
  },
  'the-empty-room': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Canopy Bed from \'Verscheyden Schrynwerck (...)\' [\'Plusieurs Menuiseries (...)\']',
    artist: 'Paul Vredeman de Vries',
    date: '1658',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/428368',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.2287,
  },
  'the-examined-life': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Perspectiva Corporum Regularium',
    artist: 'Jost Amman',
    date: '1568',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/339008',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.4357,
  },
  'the-fear-you-feed': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Knight, Death and the Devil',
    artist: 'Albrecht Dürer',
    date: '1513',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/377280',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7764,
  },
  'the-freedom-of-less': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Lute Player and Harpist, from Scenes of Daily Life',
    artist: 'Israhel van Meckenem',
    date: 'n.d. (late 15th century)',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336177',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.6931,
  },
  'the-ghost-in-the-engine': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Sectioned skull in profile to left with the left side of the cranium removed, after Leonardo da Vinci',
    artist: 'Wenceslaus Hollar, after Leonardo da Vinci',
    date: '1651',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/360714',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.1348,
  },
  'the-gilded-cage-you-built-yourself': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Le Chat Guettant L\'Oiseau en Cage (The Cat Watching the Bird in the Cage), plate 10 from "Lux Claustri ou La Lumière du Cloitre" (The Light of the Cloisters)',
    artist: 'Jacques Callot',
    date: '1621–35',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/419182',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7785,
  },
  'the-god-after-god': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Corinthian capital, from "Speculum Romanae Magnificentiae"',
    artist: 'Agostino Veneziano (Agostino dei Musi)',
    date: '1536',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/345489',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.204,
  },
  'the-green-eyed-god': {
    institution: 'Rijksmuseum',
    title: 'Afgunst (Invidia)',
    artist: 'Lucas Vorsterman (I) (vermeld op object)',
    date: '1619 - 1675',
    objectUrl: 'https://www.rijksmuseum.nl/en/collection/RP-P-1905-3954',
    rights: 'Public Domain (Rijksmuseum record asserts https://creativecommons.org/publicdomain/zero/1.0/ on the object and https://creativecommons.org/publicdomain/mark/1.0/ on the image)',
    aspect: 0.7562,
  },
  'the-inner-citadel': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Siege of a Fortress',
    artist: 'Albrecht Dürer',
    date: 'n.d.',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/387590',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.6764,
  },
  'the-intelligence-of-wounds': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Two Flayed Men and Their Skeletons',
    artist: 'Domenico del Barbiere',
    date: 'ca. 1540–45',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/358117',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.3873,
  },
  'the-letting-go': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Water, from series The Four Elements',
    artist: 'Reinier Nooms, called Zeeman',
    date: '17th century',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/371400',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 2.6087,
  },
  'the-life-you-think-you-want': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Whore of Babylon, from "The Apocalypse"',
    artist: 'Albrecht Dürer',
    date: '1498',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336214',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7382,
  },
  'the-mask-behind-the-face': {
    institution: 'Rijksmuseum',
    title: 'Vrouw met masker en fantasie hoofdbedekking',
    artist: 'anonymous',
    date: 'ca. 1535 - ca. 1598',
    objectUrl: 'https://www.rijksmuseum.nl/en/collection/RP-P-H-H-864',
    rights: 'Public Domain (Rijksmuseum record asserts https://creativecommons.org/publicdomain/zero/1.0/ on the object and https://creativecommons.org/publicdomain/mark/1.0/ on the image)',
    aspect: 0.7493,
  },
  'the-mask-that-speaks': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Mask',
    artist: 'Stefano della Bella',
    date: '',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/376683',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.6736,
  },
  'the-meaning-of-pain': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Noblewoman, from "The Dance of Death"',
    artist: 'Hans Holbein the Younger',
    date: 'ca. 1526, published 1538',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336311',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7931,
  },
  'the-mind-that-wont-be-quiet': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Melencolia I',
    artist: 'Albrecht Dürer',
    date: '1514',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336228',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7917,
  },
  'the-price-of-everything': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Four Horsemen, from "The Apocalypse"',
    artist: 'Albrecht Dürer',
    date: '1498',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336215',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7361,
  },
  'the-problem-of-evil': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Job Tempted by a Demon; verso text from the Speculum Patientiae',
    artist: 'Hans Baldung (called Hans Baldung Grien)',
    date: '1509',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/416033',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7403,
  },
  'the-public-wreckage': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Frontispiece from "Vedute di Roma"',
    artist: 'Giovanni Battista Piranesi',
    date: '1748',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/362914',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.3445,
  },
  'the-question-behind-every-question': {
    institution: 'The Metropolitan Museum of Art',
    title: 'St. Jerome in the Wilderness',
    artist: 'Nicolò Boldrini (after Titian)',
    date: 'mid-16th century',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/358295',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.3688,
  },
  'the-self-that-isnt-there': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Vertical Panel with Design for a Mirror',
    artist: 'Abraham de Bruyn',
    date: '1580–1600',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/423644',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7139,
  },
  'the-serious-work-of-play': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Quis evadet?',
    artist: 'Hendrick Goltzius',
    date: '1594',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/363640',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7354,
  },
  'the-silent-altar': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Censer',
    artist: 'Martin Schongauer',
    date: '1470–1491',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/336167',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7646,
  },
  'the-stain-that-stays': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Hands and arms',
    artist: 'Wenceslaus Hollar',
    date: '1644–52',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/360716',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 2.6766,
  },
  'the-story-you-keep-telling': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Plate 6 from "Los Caprichos":  Nobody knows himself (Nadie se conoce)',
    artist: 'Goya (Francisco de Goya y Lucientes)',
    date: '1799',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/377785',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7285,
  },
  'the-trouble-with-desire': {
    institution: 'Rijksmuseum',
    title: 'Jongen met vogelkooi',
    artist: 'anonymous',
    date: '1625 - 1675',
    objectUrl: 'https://www.rijksmuseum.nl/en/collection/RP-P-1905-2828',
    rights: 'Public Domain (Rijksmuseum record asserts https://creativecommons.org/publicdomain/zero/1.0/ on the object and https://creativecommons.org/publicdomain/mark/1.0/ on the image)',
    aspect: 0.8076,
  },
  'the-undoing-of-two': {
    institution: 'Rijksmuseum',
    title: 'Ruins of Brederode Castle from the Southwest',
    artist: 'Hercules Segers',
    date: 'c. 1618 - c. 1622',
    objectUrl: 'https://www.rijksmuseum.nl/en/collection/RP-P-H-OB-855',
    rights: 'Public Domain (Rijksmuseum record asserts https://creativecommons.org/publicdomain/zero/1.0/ on the object and https://creativecommons.org/publicdomain/mark/1.0/ on the image)',
    aspect: 1.3611,
  },
  'the-unfinished-life': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Quis evadet?',
    artist: 'Hendrick Goltzius',
    date: '1594',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/363640',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7354,
  },
  'the-uninvited-guest': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Two Flayed Men and Their Skeletons',
    artist: 'Domenico del Barbiere',
    date: 'ca. 1540–45',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/358117',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.3873,
  },
  'the-vessel-and-the-flame': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Job\'s Evil Dreams',
    artist: 'William Blake',
    date: '1825–26',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/383290',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7875,
  },
  'the-virtue-of-surrender': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Windblown bamboo (清風高節圖)',
    artist: 'Xia Chang',
    date: 'ca. 1460',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/44590',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.3583,
  },
  'the-weight-of-things': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Three Vessels',
    artist: 'Hieronymus Hopfer',
    date: '16th century',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/360203',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7514,
  },
  'what-carried-you-through': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Brussels Packet',
    artist: 'Wenceslaus Hollar',
    date: '1625–77',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/361534',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.6125,
  },
  'what-does-your-anger-want': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Le Colère, from "Caractères des passions, gravés sur les desseins de l\'illustre Monsieur Le Brun"',
    artist: 'Sébastien Le Clerc, le Jeune',
    date: '1695–1720',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/681484',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.9073,
  },
  'what-you-leave-behind': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Cœnotaphiorum (12)',
    artist: 'Hans Vredeman de Vries',
    date: '1563',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/402140',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 1.2478,
  },
  'when-silence-becomes-complicity': {
    institution: 'The Metropolitan Museum of Art',
    title: 'The Sermon of St. John the Baptist',
    artist: 'Lucas Cranach the Elder',
    date: '1516',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/623817',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7021,
  },
  'when-words-arent-enough': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Harpocrates, the God of Silence',
    artist: 'Jan Muller, after Harmen Jansz Muller',
    date: '1593',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/374017',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.7764,
  },
  'where-do-you-belong': {
    institution: 'Rijksmuseum',
    title: 'Trap met de vier grenspalen',
    artist: 'Hubert Robert (mentioned on object)',
    date: '1763',
    objectUrl: 'https://www.rijksmuseum.nl/en/collection/RP-P-1953-23',
    rights: 'Public Domain (Rijksmuseum record asserts https://creativecommons.org/publicdomain/zero/1.0/ on the object and https://creativecommons.org/publicdomain/mark/1.0/ on the image)',
    aspect: 0.6826,
  },
  'why-do-i-keep-going-back': {
    institution: 'The Metropolitan Museum of Art',
    title: 'Saint Michael Fighting the Dragon, from "The Apocalypse"',
    artist: 'Albrecht Dürer',
    date: '1511',
    objectUrl: 'https://www.metmuseum.org/art/collection/search/368339',
    rights: 'Public Domain (Met Open Access, CC0 1.0 Universal)',
    aspect: 0.6903,
  },
};
